### ISSUE TITLE
No consoles or Roms

### ISSUE THREAD

**Issue by Ridle** [CamHenlin/PlexGameLauncher#3]
Hey I installed the gamelauncher numerous times with he following:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/CamHenlin/PlexGameLauncher/master/autoinstall.rb)"

and all goes well, until I restart plex, and I want to select a console. Nothing shows up, allso when I look for Roms, nothing shows up.

Please advice / help me out.
Kind regards
Dennis de Groot

**Comment by CamHenlin** [comment]
Hi Dennis, are you putting your ROMs into the correct system directory in your Documents? The path should be ~/Documents/ROMs/<system title> 

After that, you need to go to the maintenance menu in Plex Game Launcher inside of Plex, and have it scan for new ROMs. Then you can go under systems and your games should show up. Please let me know if that's more clear

**Comment by Ridle** [comment]
Yeah that is where my roms are.
I have: Documents/ROMs/console/super_mario.7z

I deinstalled everything last night and will try to reinstall it tonight, run the Ruby code to install the game launcher and will report back to you.

Hope you can help me out to get this working.

Kind regards
Dennis de Groot

**Comment by CamHenlin** [comment]
Hi Dennis, I'm sorry but the game launcher is not built to handle 7zip files. You'll need to unzip the ROMs first

**Comment by Ridle** [comment]
Ok, but how do you explain that I don't see any consoles under "Consoles" in the gamelauncher?

**Comment by CamHenlin** [comment]
That's correct, it will only show consoles that it has found ROMs for

**Comment by Ridle** [comment]
Ahh ok, and what extension should my SNES roms be?

**Comment by Ridle** [comment]
Is the extension .sfc good?

**Comment by CamHenlin** [comment]
SMC and SFC are the most common, your 7zip file will probably unzip to one of those

**Comment by Ridle** [comment]
Ok will try this tonight, it it works, next step: get my PS3 controller to work with the games :)

**Comment by CamHenlin** [comment]
That's what I use! Good luck!

**Comment by Ridle** [comment]
Can you tell me what I need to make my PS3 controller to work with this?
So that when I get this working I can immediatly start with the next step :)

**Comment by Ridle** [comment]
Hey CamHelin,

It worked, i can see roms now but now I have the following issue:

When i select the rom i want to play (Super Mario) it says "Can't connect to the selected server or the content is no longer available".

I have the latest Plex Server installed and I have Plex App installed on my Samsung smart TV (UE46D6500 is a D-Series (2011) model).
Plex App information: 1.016

Please advice.

Kind regards
Dennis de Groot

**Comment by CamHenlin** [comment]
Sorry, since there are so many controller options, we decided that we really can't help people get those setup. The easiest way is to use a program such as GamePad Companion (from the App Store) and map your controller's keys to keyboard buttons, I believe that's what many users do.

**Comment by Ridle** [comment]
Ok, than I don't see the use for this.
You can just install the emulator instead of plex server + plex app.

Seems a bit weird to me.
Thought this would be the system for me.

Ah well too bad.
