### ISSUE TITLE
Doesn't recognize ROM's are in folders?

### ISSUE THREAD

**Issue by jeffk395** [CamHenlin/PlexGameLauncher#5]
When performing initial scan after installation as per instructions, the ROMs fail to scrape - all lists are empty. Even unknown ROMS list. It does say "Please Wait" during the scan, but nothing happens after that.

How can I get these to be recognized?

![screen shot 2015-01-28 at 7 39 48 pm](https://cloud.githubusercontent.com/assets/10749875/5950299/3a71ac30-a726-11e4-9196-f90bfe03fc42.png)
![screen shot 2015-01-28 at 7 44 31 pm](https://cloud.githubusercontent.com/assets/10749875/5950301/3a7c6be8-a726-11e4-896a-4f86804acba5.png)
![screen shot 2015-01-28 at 7 40 13 pm](https://cloud.githubusercontent.com/assets/10749875/5950302/3a7cb580-a726-11e4-950f-abfec223daae.png)
![screen shot 2015-01-28 at 7 40 01 pm](https://cloud.githubusercontent.com/assets/10749875/5950300/3a7bf91a-a726-11e4-907d-05ff29aa34c6.png)

**Comment by CamHenlin** [comment]
Hi, thanks for your bug report. Could you post the contents of the most recent com.plexapp.plugins.gamelauncher.log? It's located at ~/Library/Logs/PMS\ Plugin\ Logs/com.plexapp.plugins.gamelauncher.log

**Comment by jeffk395** [comment]
it's too long to post and I cannot export as an image. Email address?

**Comment by jeffk395** [comment]
Actually - update. I went to get the logs and noticed that all the roms are being flagged as unknown roms. They are showing up under the correct console type. As of now, nothing is listed under list all games nor under each of the respective console types.

**Comment by CamHenlin** [comment]
Sure, can you email it to henlin@uoregon.edu?

**Comment by CamHenlin** [comment]
Looks like gamefaqs changed their API (or removed it) and our grabber is no longer able to identity any of your ROMs because of that. I'll update code this evening to either fix gamefaqs or remove it and use a different grabber instead. Sorry for the inconvenience!

**Comment by jeffk395** [comment]
Can I change the grabber from my end or does the whole thing have to be reconfig’d?

-- 
Jeff Kunkel Jr.
Sent with Airmail

On January 28, 2015 at 9:13:24 PM, Cameron Henlin (notifications@github.com) wrote:

Looks like gamefaqs changed their API (or removed it) and our grabber is no longer able to identity any of your ROMs because of that. I'll update code this evening to either fix gamefaqs or remove it and use a different grabber instead. Sorry for the inconvenience!

**Comment by CamHenlin** [comment]
I'm not in front of the computer at the moment, but I believe that you can change the grabber precedence in the settings. Anything other than gamefaqs will probably work if you run another scan

**Comment by jeffk395** [comment]
I put GameFaqs at the bottom of the order - looks like a no-go.

No biggie - just drop me a quick line when you update your thing.

Will I have to uninstall and re-install the plugin when its updated via git-hub just to be safe?


Jeff Kunkel Jr.
Manager, IT Operations
Axial Networks, Inc.
45 East 20th Street, 12th Floor
New York, NY 10003
Email - jeff.kunkel@axial.net
Office - (917) 639-5326
Mobile - (203) 451-2030



Axial Blog | Connect on LinkedIn | Twitter @AxialCo

On January 28, 2015 at 9:17:51 PM, Cameron Henlin (notifications@github.com) wrote:

I'm not in front of the computer at the moment, but I believe that you can change the grabber precedence in the settings. Anything other than gamefaqs will probably work if you run another scan
